configs:
  indexMap:
    enterprise:
      fsPath: C:\Users\zhenqiang.huang\Desktop\searchprocess\pydata\shard_index
      fsPathName: fsindex
      incrPath: C:\Users\zhenqiang.huang\Desktop\searchprocess\pydata\shard_index
      incrPathName: mmapindex
      shardNum: 10
      fieldMap:
        id:
          fieldName: id
          analyzerType: 1
          fieldType: 2
          stored: 1
          dbFieldFlag: 1
        pinyin:
          fieldName: pinyin
          analyzerType: 4
          fieldType: 1
          stored: 0
          dbFieldFlag: 0
          parentField: name
        jianpin:
          fieldName: jianpin
          analyzerType: 3
          fieldType: 1
          stored: 0
          dbFieldFlag: 0
          parentField: name
        name:
          fieldName: name
          analyzerType: 1
          fieldType: 1
          stored: 1
          dbFieldFlag: 1
        fuzz_name:
          fieldName: fuzz_name
          analyzerType: 1
          fieldType: 2
          stored: 0
          dbFieldFlag: 0
          parentField: name
        fuzz_used_name:
          fieldName: fuzz_used_name
          analyzerType: 1
          fieldType: 2
          stored: 0
          dbFieldFlag: 0
          parentField: used_name
        used_name:
          fieldName: used_name
          analyzerType: 1
          fieldType: 1
          stored: 1
          dbFieldFlag: 1
        product_brand_names:
          fieldName: product_brand_names
          analyzerType: 1
          fieldType: 1
          stored: 1
          dbFieldFlag: 1
        brand_names_algo:
          fieldName: brand_names_algo
          analyzerType: 1
          fieldType: 1
          stored: 1
          dbFieldFlag: 1
        app_name:
          fieldName: app_name
          analyzerType: 1
          fieldType: 1
          stored: 1
          dbFieldFlag: 1
        oper_name:
          fieldName: oper_name
          analyzerType: 5
          fieldType: 1
          stored: 1
          specialChar: 32
          dbFieldFlag: 1
        oper_name_one:
          fieldName: oper_name_one
          analyzerType: 5
          fieldType: 1
          stored: 1
          specialChar: 32
          dbFieldFlag: 1
        stock_name_short_array:
          fieldName: stock_name_short_array
          analyzerType: 1
          fieldType: 1
          stored: 1
          dbFieldFlag: 1
        eid:
          fieldName: eid
          analyzerType: 1
          fieldType: 2
          stored: 1
          dbFieldFlag: 1
        company_id:
          fieldName: company_id
          analyzerType: 1
          fieldType: 2
          stored: 1
          dbFieldFlag: 1
        stock_code_new_array:
          fieldName: stock_code_new_array
          analyzerType: 1
          fieldType: 2
          stored: 1
          dbFieldFlag: 1
        credit_no:
          fieldName: credit_no
          analyzerType: 1
          fieldType: 2
          stored: 1
          dbFieldFlag: 1