configs:
  indexMap:
    enterprise:

      dbUrl: jdbc:mysql://url:port/db
      dbTableName: table
      dbUserName: username
      dbPass: pass

      #      fsPath: D:\searchfile\v5\shard-index-sug
      #      fsPath: D:\searchfile\shard_single_index
      fsPath: /appstore/bird/bird-search-multirecall/shard_index_fs
      aliaPath: /appstore/bird/bird-search-multirecall/shard_index_alia
      fsPathName: fsindex
      #      incrPath: D:\searchfile\shard_single_index
      #      incrPathName: mmapindex
      shardNum: 50
      switchIndex: /appstore/bird/bird-search-multirecall/switch.data
      fieldMap:
        id:
          fieldName: id
          analyzerType: 1
          fieldType: 1
          stored: 1
          dbFieldFlag: 1
        all_name_pinyin:
          fieldName: all_name_pinyin
          analyzerType: 4
          fieldType: 1
          stored: 0
          dbFieldFlag: 0
          parentField: name
        all_used_name_pinyin:
          fieldName: all_used_name_pinyin
          analyzerType: 4
          fieldType: 1
          stored: 0
          dbFieldFlag: 0
          parentField: name
        name_pinyin:
          fieldName: name_pinyin
          analyzerType: 2
          fieldType: 1
          stored: 0
          dbFieldFlag: 0
          parentField: name
        used_name_pinyin:
          fieldName: used_name_pinyin
          analyzerType: 2
          fieldType: 1
          stored: 0
          dbFieldFlag: 0
          parentField: used_name
        name_jianpin:
          fieldName: name_jianpin
          analyzerType: 3
          fieldType: 1
          stored: 0
          dbFieldFlag: 0
          parentField: name
        used_name_jianpin:
          fieldName: used_name_jianpin
          analyzerType: 3
          fieldType: 1
          stored: 0
          dbFieldFlag: 0
          parentField: used_name
        name:
          fieldName: name
          analyzerType: 1
          fieldType: 1
          stored: 1
          dbFieldFlag: 1
        fuzz_name:
          fieldName: fuzz_name
          analyzerType: 7
          fieldType: 1
          stored: 0
          dbFieldFlag: 0
          parentField: name
        fuzz_used_name:
          fieldName: fuzz_used_name
          analyzerType: 7
          fieldType: 1
          stored: 0
          dbFieldFlag: 0
          parentField: used_name
        single_fuzz_name:
          fieldName: single_fuzz_name
          analyzerType: 8
          fieldType: 1
          stored: 0
          dbFieldFlag: 0
          parentField: name
        single_fuzz_used_name:
          fieldName: single_fuzz_used_name
          analyzerType: 8
          fieldType: 1
          stored: 0
          dbFieldFlag: 0
          parentField: used_name
        used_name:
          fieldName: used_name
          analyzerType: 1
          fieldType: 1
          stored: 1
          dbFieldFlag: 1
        product_brand_names:
          fieldName: product_brand_names
          analyzerType: 5
          fieldType: 1
          stored: 1
          specialChar: 59
          dbFieldFlag: 1
        brand_names_algo:
          fieldName: brand_names_algo
          analyzerType: 5
          fieldType: 1
          stored: 1
          specialChar: 59
          dbFieldFlag: 1
        app_name:
          fieldName: app_name
          analyzerType: 5
          fieldType: 1
          stored: 1
          specialChar: 59
          dbFieldFlag: 1
        oper_name:
          fieldName: oper_name
          analyzerType: 5
          fieldType: 1
          stored: 1
          specialChar: 59
          dbFieldFlag: 1
        oper_name_one:
          fieldName: oper_name_one
          analyzerType: 5
          fieldType: 1
          stored: 1
          specialChar: 59
          dbFieldFlag: 1
        stock_name_short_array:
          fieldName: stock_name_short_array
          analyzerType: 5
          fieldType: 1
          stored: 1
          specialChar: 59
          dbFieldFlag: 1
        eid:
          fieldName: eid
          analyzerType: 6
          fieldType: 1
          stored: 1
          dbFieldFlag: 1
        company_id:
          fieldName: company_id
          analyzerType: 6
          fieldType: 1
          stored: 1
          dbFieldFlag: 1
        stock_code_new_array:
          fieldName: stock_code_new_array
          analyzerType: 5
          fieldType: 1
          stored: 1
          specialChar: 59
          dbFieldFlag: 1
        credit_no:
          fieldName: credit_no
          analyzerType: 6
          fieldType: 1
          stored: 1
          dbFieldFlag: 1
        found_years:
          fieldName: found_years
          analyzerType: 1
          fieldType: 3
          stored: 1
          dbFieldFlag: 1
        company_score:
          fieldName: company_score
          analyzerType: 1
          fieldType: 4
          stored: 1
          dbFieldFlag: 1
        reg_capi:
          fieldName: reg_capi
          analyzerType: 1
          fieldType: 4
          stored: 1
          dbFieldFlag: 1
        social_security_num:
          fieldName: social_security_num
          analyzerType: 1
          fieldType: 3
          stored: 1
          dbFieldFlag: 1
        type_new:
          fieldName: type_new
          analyzerType: 6
          fieldType: 1
          stored: 1
          dbFieldFlag: 1
        category_new:
          fieldName: category_new
          analyzerType: 6
          fieldType: 1
          stored: 1
          dbFieldFlag: 1
        status:
          fieldName: status
          analyzerType: 6
          fieldType: 1
          stored: 1
          dbFieldFlag: 1
        address_code_prov:
          fieldName: address_code_prov
          analyzerType: 6
          fieldType: 1
          stored: 1
          dbFieldFlag: 1
        address_code_city:
          fieldName: address_code_city
          analyzerType: 6
          fieldType: 1
          stored: 1
          dbFieldFlag: 1
        address_code_dist:
          fieldName: address_code_dist
          analyzerType: 6
          fieldType: 1
          stored: 1
          dbFieldFlag: 1
        industry_code_1:
          fieldName: industry_code_1
          analyzerType: 6
          fieldType: 1
          stored: 1
          dbFieldFlag: 1
        industry_code_2:
          fieldName: industry_code_2
          analyzerType: 6
          fieldType: 1
          stored: 1
          dbFieldFlag: 1
        industry_code_3:
          fieldName: industry_code_3
          analyzerType: 6
          fieldType: 1
          stored: 1
          dbFieldFlag: 1
        industry_code_4:
          fieldName: industry_code_4
          analyzerType: 6
          fieldType: 1
          stored: 1
          dbFieldFlag: 1
